seed: 0
task: prediction
dataset: Feas2
save_test: False
save_params: False

train_batch_size: 512
val_batch_size: 512
test_batch_size: 512
max_epoch: 100
val_freq: 1
logging_freq: 20
early_stopping_epoch: 30
early_stopping_metric: AUROC
bootstrap_num: 100
ecg_length: 6080
features_num: 12
spectrogram_height: 256
spectrogram_width: 256

model:
  name: GRU
  mode: train
  args:
hidden_dim: 32
layer_num: 4
dropout: 0.1

optimizer:
  name: Adam
  args:
lr: 0.001
weight_decay: 0.

scheduler:
  name: ExpLR
  args:
gamma: 0.995

criterion:
  binary_entropy:
    reduction: mean

val_metrics:
  Accuracy:
    args: None
  Predictivity:
    args: None
  Negative_Predictivity:
    args: None
  Recall:
    args: None
  AUROC:
    args: None
  AUPRC:
    args: None
  F1:
    args: None

test_metrics:
  Accuracy:
    args: None
  Predictivity:
    args: None
  Negative_Predictivity:
    args: None
  Recall:
    args: None
  AUROC:
    args: None
  AUPRC:
    args: None
  F1:
    args: None

processed_data_path: C:\Users\ZC\Documents\GitHub\IIB_Project\data\processed
log_data_path: C:\Users\ZC\Documents\GitHub\IIB_Project\logs